### ISSUE TITLE
Native Script 7 Support

### ISSUE THREAD

**Issue by harishchopra86** [triniwiz/nativescript-tooltip#8]
Is it going to support native script 7

**Comment by triniwiz** [comment]
Yes I've not reached this plugin yet but it's in the todo list

**Comment by harishchopra86** [comment]
Hey @triniwiz ,

Just checking in if you got change to look into tooltip plugin.
I need to use it into our application which is using NativeScript 7. 

Thanks,
Harish

**Comment by csimpi** [comment]
@triniwiz still nothing?

**Comment by triniwiz** [comment]
@csimpi I'll drop something for it very soon

**Comment by csimpi** [comment]
ping :)

**Comment by triniwiz** [comment]
Published `@triniwiz/nativescript-tooltip` [repo](https://github.com/triniwiz/nativescript-plugins) & [docs](https://triniwiz.github.io/nativescript-plugins/api-reference/tooltip.html#installing)
